#!/usr/bin/env ruby
# Discovers the GitHub Pages *project* sites of the configured owner that are
# served under the host and expose a sitemap.xml (HTTP 200), and writes them to
# _data/pages_sitemaps.yml. robots.txt renders one `Sitemap:` line per entry
# (plus the fixed host sitemap), so the host's sitemap declarations stay in sync
# with what is actually published — no hand-editing.
#
# Why 200-only: a declared-but-missing sitemap wastes crawl budget and teaches
# crawlers to distrust the file. Repos with a custom domain (CNAME) serve their
# Pages elsewhere, so probing <host>/<repo>/sitemap.xml returns 404/redirect for
# them and they are naturally excluded — no special-casing needed.
#
# Config: _data/robots_sync.yml (host, owner, exclude).
# Output: _data/pages_sitemaps.yml (generated — do not hand-edit).
#
# Usage: ruby scripts/sync_robots_sitemaps.rb
#   env DRY_RUN=1     — print the result without writing the file
#   env GITHUB_TOKEN  — optional, raises the GitHub API rate limit (set in CI)
#
# Stdlib only — no bundle install needed. Idempotent: the file is rewritten only
# when the set of live sitemaps changes, so an unchanged run produces no diff
# (and therefore no commit / no deploy).

require 'net/http'
require 'json'
require 'yaml'
require 'uri'

ROOT = File.expand_path('..', __dir__)
DRY_RUN = !ENV['DRY_RUN'].to_s.empty?
TOKEN = ENV['GITHUB_TOKEN'].to_s

config = YAML.safe_load(File.read(File.join(ROOT, '_data', 'robots_sync.yml'), encoding: 'UTF-8'))
HOST = config.fetch('host')
OWNER = config.fetch('owner')
EXCLUDE = config.fetch('exclude', []).map(&:downcase)
OUTFILE = File.join(ROOT, '_data', 'pages_sitemaps.yml')

def get_json(url)
  uri = URI(url)
  headers = { 'User-Agent' => 'jekyll-robots-sync', 'Accept' => 'application/vnd.github+json' }
  headers['Authorization'] = "Bearer #{TOKEN}" unless TOKEN.empty?
  res = Net::HTTP.start(uri.host, uri.port, use_ssl: true, open_timeout: 15, read_timeout: 30) do |http|
    http.get(uri.request_uri, headers)
  end
  abort "GitHub API error: HTTP #{res.code} for #{url}" unless res.is_a?(Net::HTTPSuccess)
  JSON.parse(res.body)
end

# Returns the body of url following up to `limit` redirects, or nil on any
# non-200 (including redirects off-host, which is what a custom domain does).
def fetch_ok(url, limit = 3)
  return nil if limit < 0
  uri = URI(url)
  res = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https', open_timeout: 15, read_timeout: 30) do |http|
    http.get(uri.request_uri, { 'User-Agent' => 'jekyll-robots-sync' })
  end
  case res
  when Net::HTTPSuccess then res.body
  when Net::HTTPRedirection then fetch_ok(res['location'], limit - 1)
  end
rescue StandardError
  nil
end

def pages_repos
  repos = []
  (1..10).each do |page|
    batch = get_json("https://api.github.com/users/#{OWNER}/repos?per_page=100&page=#{page}&sort=full_name")
    repos.concat(batch)
    break if batch.length < 100
  end
  repos.select { |r| r['has_pages'] && !r['fork'] }
        .map { |r| r['name'] }
        .reject { |name| EXCLUDE.include?(name.downcase) }
        .sort_by(&:downcase)
end

live = []
skipped = []
pages_repos.each do |name|
  body = fetch_ok("https://#{HOST}/#{name}/sitemap.xml")
  if body
    urls = body.scan(/<loc>/).length
    live << { 'name' => name, 'urls' => urls }
    warn "  live   #{name} (#{urls} URLs)"
  else
    skipped << name
    warn "  no map #{name}"
  end
end

header = <<~YAML
  # GENERATED by scripts/sync_robots_sitemaps.rb — do not edit by hand.
  #
  # #{OWNER}-owned GitHub Pages project sites under #{HOST} that expose a
  # sitemap.xml (HTTP 200). robots.txt renders one `Sitemap:` line per entry.
  # #{skipped.length} other Pages site(s) are live but ship no sitemap and are
  # omitted: #{skipped.empty? ? '(none)' : skipped.join(', ')}
YAML

output = header + YAML.dump(live).sub(/\A---\n/, '')

if DRY_RUN
  puts output
  warn "\nDRY_RUN: #{live.length} sitemap(s) would be written, #{skipped.length} omitted."
elsif File.exist?(OUTFILE) && File.read(OUTFILE, encoding: 'UTF-8') == output
  warn "No change: #{live.length} live sitemap(s)."
else
  File.write(OUTFILE, output)
  warn "Wrote #{OUTFILE}: #{live.length} live sitemap(s), #{skipped.length} omitted."
end
