name: Refresh AJ | Build and deploy Jekyll site to GitHub Pages | 
on:
  schedule:
    - cron:  '0 10 * * *' # Runs every day at 3am
  push:	
    branches: [ "master", "main" ]
#
jobs:
  #
  build:
    #
    runs-on: ubuntu-latest
    #
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: 🎩 Install Jekyll
        run: |
          sudo gem install bundler jekyll
          sudo bundle install
      - name: 🧹 Clean site
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
          fi
      - name: 🔨 Build site
        run: bundle exec jekyll build -d docs
      - name: 🧪 Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🧪 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
