
name: Build and deploy Jekyll site to GitHub Pages | Refresh
#
on:
  schedule:
    - cron:  '0 3 * * *' # Runs every day at 3am
  push:	
    branches: [ "master", "main" ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
