name: Update Activity FILE

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's FILE with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: Allan-Nava/github-activity-file@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        with:
          FILE: './_posts/2020-09-17-allan-nava-workflows.markdown'
        #
