name: Uptime Monitor
#
on:
  schedule:
  # Run every 10 minutes
  - cron: '*/10 * * * *' 
#
jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Uptime Check
    steps:
    - name: Ping Site
    uses: srt32/uptime@v0.2
    with:
      url-to-hit: "https://allan-nava.github.io/"
      expected-statuses: "200"
#
#
